source 'https://rubygems.org'

gem 'rails', '5.1.3'

gem 'activerecord-import'
gem 'bootstrap-sass'
gem 'bootswatch-rails'
gem 'coffee-rails'
gem 'devise', git: 'https://github.com/plataformatec/devise'
gem 'dotenv-rails'
gem 'exception_notification'
gem 'faraday'
gem 'font-awesome-rails'
gem 'google-analytics-rails'
gem 'graphiql-rails'
gem 'graphql'
gem 'graphql-batch'
gem 'hamlit'
gem 'jquery-rails'
gem 'kaminari'
gem 'mysql2'
gem 'newrelic_rpm'
gem 'omniauth'
gem 'omniauth-github'
gem 'puma'
gem 'rack-user_agent'
gem 'ridgepoler-rails'
gem 'sassc-rails'
gem 'sentry-raven'
gem 'sprockets'
gem 'uglifier'
gem 'webpacker'

group :development do
  gem 'capistrano'
  gem 'capistrano-bundler'
  gem 'capistrano-rails'
  gem 'capistrano-rbenv'
  gem 'foreman'
  gem 'silencer'
  gem 'spring'
  gem 'spring-commands-rspec'
  gem 'listen'
end

group :development, :test do
  gem 'factory_girl'
  gem 'pry-byebug'
  gem 'pry-doc'
  gem 'pry-rails'
  gem 'rspec-rails'
  gem 'timecop'
end
