source 'https://rubygems.org'

gem 'rails', '4.2.0'

gem 'activerecord-import'
gem 'bootstrap-sass'
gem 'bootswatch-rails'
gem 'coffee-rails'
gem 'devise'
gem 'dotenv-rails'
gem 'each_with_rank'
gem 'font-awesome-rails'
gem 'foreman'
gem 'haml-rails'
gem 'jbuilder'
gem 'jquery-rails'
gem 'kaminari'
gem 'mysql2'
gem 'octokit'
gem 'omniauth'
gem 'omniauth-github'
gem 'progress_bar'
gem 'rack-user_agent'
gem 'sass-rails'
gem 'sunspot_rails'
gem 'sunspot_solr'
gem 'therubyracer'
gem 'uglifier'
gem 'unicorn'

group :development, :test do
  gem 'capistrano'
  gem 'capistrano-bundler'
  gem 'capistrano-rails'
  gem 'capistrano-rbenv'
  gem 'pry-byebug'
  gem 'pry-doc'
  gem 'pry-rails'
  gem 'silencer'
  gem 'spring'
end
