source 'https://rubygems.org'

gem 'rails', '4.2.0'

gem 'bootstrap-sass', '~> 2.3.2'
gem 'activerecord-import'
gem 'coffee-rails'
gem 'dotenv-rails'
gem 'each_with_rank'
gem 'foreman'
gem 'haml-rails'
gem 'jbuilder'
gem 'jquery-rails'
gem 'mysql2'
gem 'octokit'
gem 'sass-rails'
gem 'therubyracer'
gem 'uglifier'
gem 'unicorn'

group :development, :test do
  gem 'capistrano'
  gem 'capistrano-bundler'
  gem 'capistrano-rails'
  gem 'capistrano-rbenv'
  gem 'pry-byebug'
  gem 'pry-doc'
  gem 'pry-rails'
  gem 'silencer'
  gem 'spring'
end
