DEPLOY_HOST = 'excloud'
DEPLOY_TO   = '/home/k0kubun/rank'

desc 'Deploy rank to linux'
task :deploy do
  system('GOOS=linux GOARCH=amd64 go build')
  system("ssh #{DEPLOY_HOST} 'mkdir -p #{DEPLOY_TO}'")
  system("scp rank #{DEPLOY_HOST}:#{DEPLOY_TO}")
end

task default: :deploy
