#!/bin/bash

export QUEUES=default
export DISC_CONCURRENCY=25
export DISQUE_NODES=localhost:7711
export DISQUE_TIMEOUT=2000
export DISQUE_CYCLE=1000
unset DISQUE_AUTH

# disc -r ./disc_init.rb
disc -r celluloid/current -r ./disc_init.rb
